[build-dependencies]
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"

[dependencies]
async-trait = "0.1.80"
futures = "0.3.30"
serde = "1.0.203"
serde_json = "1.0.120"
tokio = "1.38.0"
tokio-tungstenite = "0.23.1"

[lib]
crate-type = ["rlib"]
name = "Echo"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
description = "ğŸ“£â€Echoâ€â€”"
license = "MIT"
name = "Echo"
repository = "HTTPS://GitHub.Com/CodeEditorLand/Echo"
version = "0.0.0"
edition = "2021"
publish = false
