[build-dependencies]
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.15"

[dependencies]
async-trait = "0.1.81"
futures = "0.3.30"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
tokio-tungstenite = "0.23.1"

[lib]
crate-type = ["rlib"]
name = "Echo"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
description = "ğŸ“£â€Echoâ€â€”"
license = "MIT"
name = "Echo"
repository = "HTTPS://GitHub.Com/CodeEditorLand/Echo"
version = "0.0.1"
edition = "2021"
publish = false
